name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_format_validate:
    name: Check Packer Formatting and Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Create webapp.zip
        run: |
            zip -r webapp.zip ./

      - name: Run Packer Format Check
        id: fmt
        run: |
          packer fmt -check .
        continue-on-error: false

      - name: Run Packer Validate
        id: validate
        run: |
          packer init .
          packer validate .
        continue-on-error: false
      - name: Pass the AMI to Demo in AWS
        run: |
          AMI_ID=$(aws ec2 describe-images --filters "Name=name,Values=${{ steps.create_image_name.outputs.IMAGE_NAME }}" --query "Images[0].ImageId" --output text)
          echo "AMI ID: $AMI_ID" 

          TARGET_AWS_ACCOUNT="${{ secrets.AWS_DEMO_ACCOUNT_ID }}"
          echo "Target AWS Account: $TARGET_AWS_ACCOUNT"

          SNAPSHOT_ID=$(aws ec2 describe-images --image-ids $AMI_ID --query "Images[0].BlockDeviceMappings[0].Ebs.SnapshotId" --output text)
          echo "Associated Snapshot ID: $SNAPSHOT_ID"

          # Share AMI with DEMO account
          aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "Add=[{UserId=$TARGET_AWS_ACCOUNT}]"

          # Share associated snapshot with DEMO account
          aws ec2 modify-snapshot-attribute --snapshot-id $SNAPSHOT_ID --attribute createVolumePermission --operation-type add --user-ids $TARGET_AWS_ACCOUNT

          # Verify AMI sharing
          aws ec2 describe-image-attribute --image-id $AMI_ID --attribute launchPermission

          # Verify snapshot sharing
          aws ec2 describe-snapshot-attribute --snapshot-id $SNAPSHOT_ID --attribute createVolumePermission

